### ISSUE TITLE
Будет readme?

### ISSUE THREAD

**Issue by aqjw** [trin4ik/laravel-devino-api#1]

**Comment by trin4ik** [comment]
устанавливаем
`composer require trin4ik/laravel-devino-api`

мигрируем
`php artisan migrate`

настраиваем .env
```
DEVINO_LOGIN=login
DEVINO_PASSWORD=password
DEVINO_SENDER=sender
```

и используем в нужном месте
```
use Trin4ik\DevinoApi\Facades\DevinoApi AS Sms;

... 

SMS::send([
    'to' => $request->phone,
    'text' => $code . ' - ваш код подтверждения'
]);
```

использовать на свой страх и риск, компонент делается "для себя"
